version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: llm_fastapi
    environment:
      - APP=fastapi
    ports:
      - "9000:9000"
    restart: always

  streamlit_app:
    build: .
    container_name: llm_streamlit
    environment:
      - APP=streamlit
    ports:
      - "8501:8501"
    restart: always
